const RANDOM_NAME_REGEXP = /^Аноним&nbsp;ID:&nbsp;<span id="id_tag_[a-f0-9]+" style="color:rgb\(\d+,\d+,\d+\);">([^<]+)<\/span>$/

export default function parseAuthor(name, { defaultAuthorName, boardId }) {
	if (!name) {
		return
	}
	// "Anonymous&nbsp;" -> "Anonymous".
	// (`/int/` on `2ch.hk`)
	name = name.replace(/&nbsp;$/, '')
	// `Аноним`
	if (name === defaultAuthorName) {
		return
	}
	// On `/d/` board names are autogenerated from IP address hash.
	// `Аноним&nbsp;ID:&nbsp;<span id=\"id_tag_7ab0a33a\" style=\"color:rgb(116,48,218);\">Насмешливый&nbsp;Обеликс</span>`
	const randomNameMatch = name.match(RANDOM_NAME_REGEXP)
	if (randomNameMatch) {
		return randomNameMatch[1].replace('&nbsp;', '')
	}
	return name
}