import { describe, it } from './mocha'
import expectToEqual from './expectToEqual'
import parseLinks from './parseLinks'

describe('parseLinks', () => {
	it('shouldn\'t parse links in text when there are no links in text', () => {
		let post = {}
		parseLinks(post)
		expectToEqual(
			post,
			{}
		)

		post = {
			content: [
				[
					'Abc'
				]
			]
		}
		parseLinks(post)
		expectToEqual(
			post,
			{
				content: [
					[
						'Abc'
					]
				]
			}
		)

		post = {
			content: [
				{
					type: 'attachment',
					attachmentId: 1
				}
			]
		}
		parseLinks(post)
		expectToEqual(
			post,
			{
				content: [
					{
						type: 'attachment',
						attachmentId: 1
					}
				]
			}
		)
	})

	it('should parse links in text', () => {
		const post = {
			content: [
				[
					'Abc http://twitter.net/abc def'
				]
			]
		}
		parseLinks(post)
		expectToEqual(
			post,
			{
				content: [
					[
						'Abc ',
						{
							type: 'link',
							url: 'http://twitter.net/abc',
							content: 'twitter.net/abc',
							autogenerated: true
						},
						' def'
					]
				]
			}
		)
	})

	it('shouldn\'t parse links inside blocks', () => {
		const post = {
			content: [
				[
					{
						type: 'inline-quote',
						content: 'Abc http://twitter.net/abc def'
					},
					'Abc http://twitter.net/abc def',
					{
						type: 'link',
						url: 'http://twitter.net/abc',
						content: 'Abc http://twitter.net/abc def'
					}
				]
			]
		}
		parseLinks(post)
		expectToEqual(
			post,
			{
				content: [
					[
						{
							type: 'inline-quote',
							content: 'Abc http://twitter.net/abc def'
						},
						'Abc ',
						{
							type: 'link',
							url: 'http://twitter.net/abc',
							content: 'twitter.net/abc',
							autogenerated: true
						},
						' def',
						{
							type: 'link',
							url: 'http://twitter.net/abc',
							content: 'Abc http://twitter.net/abc def'
						}
					]
				]
			}
		)
	})
})
