import getPostText from 'webapp-frontend/src/utility/post/getPostText'
import trimText from 'webapp-frontend/src/utility/post/trimText'

/**
 * Adds "in-reply-to" quotes.
 * Has some CPU usage.
 */
export default function setInReplyToQuotes(content, posts, options, contentParent) {
	if (Array.isArray(content)) {
		let i = 0
		while (i < content.length) {
			const part = content[i]
			const partsCount = content.length
			setInReplyToQuotes(part, posts, options, content)
			// Check if some elements have been removed
			// (or maybe hypothetically added)
			// in which case adjust the cycle index.
			if (content.length !== partsCount) {
				i += content.length - partsCount
			}
			i++
		}
		return
	}
	// Post content can be empty.
	// Or maybe even post part's content.
	// Like `{ type: 'attachment', attachmentId: 1 }`.
	if (!content) {
		return
	}
	if (typeof content === 'string') {
		return
	}
	if (content.type === 'post-link') {
		// If the post quote for this post link has already been set then skip it.
		// This can't happen, because `.quote` property for a post link is currently
		// only set here, but added this `if` just in case of some possible future code changes.
		if (content.quote) {
			return
		}
		// If it's a post link for a post from another thread then skip it.
		if (content.threadId && content.threadId !== options.threadId) {
			return
		}
		// The post link must be in the end of a line
		// in order for a post quote to be generated.
		const index = contentParent.indexOf(content)
		if (contentParent[index + 1] !== '\n') {
			return
		}
		const post = posts.find(_ => _.id === content.postId)
		// See if there's already an existing post quote for this post link.
		const possibleQuote = contentParent[index + 2]
		if (possibleQuote && possibleQuote.type === 'inline-quote') {
			// Move the already existing post quote to the post link.
			stripLinks(possibleQuote.content)
			content.quote = possibleQuote.content
			// `kohlchan.net` has regular quotes and "inverse" quotes.
			content.quoteKind = possibleQuote.kind
			// Remove the `\n` character and the `inline-quote`.
			contentParent.splice(index + 1, 2)
		}
		// If the quoted post has been deleted then skip it.
		if (!post) {
			content.postWasDeleted = true
			return
		}
		// If the quoted post is hidden then don't add a quote it a link to it.
		if (post.hidden) {
			content.postIsHidden = true
			content.postIsHiddenRule = post.hiddenRule
			return
		}
		// If there's already an existing post quote for this post link
		// which has been just parsed then finished.
		if (content.quote) {
			return
		}
		const text = getPostText(post, {
			excludeQuotes: true,
			softLimit: 150,
			messages: options.messages
		})
		if (text) {
			// Set `content.quote` to the quoted post text abstract.
			// Doesn't set `content.post` object to prevent JSON circular structure.
			content.quote = trimText(text, 150).replace(/\n\n+/g, '\n')
			content.quoteAutogenerated = true
		}
		return
	}
	// Recurse into post parts.
	setInReplyToQuotes(content.content, posts, options, content)
}

// Inline quotes can contain hyperlinks too. For example,
// `2ch.hk` autoparses links in comment text when it's submitted
// and if there's a quoted link then it will autoparse that link.
// Such nested links would result in a React warning:
// "validateDOMNesting(...): <a> cannot appear as a descendant of <a>.".
function stripLinks(content) {
	if (Array.isArray(content)) {
		let i = 0
		while (i < content.length) {
			if (typeof content[i] === 'object') {
				// Handling just a simple case here
				// and not recursing into nested arrays.
				if (content[i].type === 'link' && typeof content[i].content === 'string') {
					content[i] = content[i].content
				}
			}
			i++
		}
	}
}