import { ReduxModule } from 'react-website'

import UserData from '../UserData/UserData'

const redux = new ReduxModule('THREAD_TRACKER')

export const getTrackedThreads = redux.simpleAction(
	_getTrackedThreads,
	'trackedThreads'
)

// Using `.action()` instead of `.simpleAction()` here
// only to listen to the "success" event in `./redux/thread.js`.
export const trackThread = redux.action(
	'TRACK_THREAD',
	(thread) => async () => {
		// Just in case the thread both doesn't have a title
		// and a title wasn't autogenerated for some reason
		// (perhaps missing `messages` for "Picture", etc).
		if (!thread.title) {
			thread.title = `#${thread.id}`
		}
		// Using a timestamp instead of a `Date` because of
		// serialization/deserialization.
		thread.addedAt = Date.now()
		UserData.addTrackedThreadsList(thread)
		return {
			// Returning `thread` here only to acess it in a listener
			// in `./redux/thread.js`.
			thread,
			trackedThreads: _getTrackedThreads()
		}
	},
	(state, { thread, trackedThreads }) => ({
		...state,
		trackedThreads
	})
)

// Using `.action()` instead of `.simpleAction()` here
// only to listen to the "success" event in `./redux/thread.js`.
export const untrackThread = redux.action(
	'UNTRACK_THREAD',
	(thread) => async () => {
		UserData.removeTrackedThreadsList(thread)
		return {
			// Returning `thread` here only to acess it in a listener
			// in `./redux/thread.js`.
			thread,
			trackedThreads: _getTrackedThreads()
		}
	},
	(state, { thread, trackedThreads }) => ({
		...state,
		trackedThreads
	})
)

redux.on('CHAN', 'GET_THREADS', (state, { boardId, threads }) => {
	// Clear expired threads from user data.
	UserData.updateThreads(boardId, threads)
	return {
	  ...state,
		trackedThreads: _getTrackedThreads()
	}
})

export const threadExpired = redux.simpleAction(
	(boardId, threadId) => {
		UserData.onThreadExpired(boardId, threadId)
		return _getTrackedThreads()
	},
	'trackedThreads'
)

export default redux.reducer({
	trackedThreads: typeof window === 'undefined' ? [] : _getTrackedThreads()
})

function _getTrackedThreads() {
	return UserData.getTrackedThreadsList()
}