import type { InlineContent } from 'social-components'
import type { ChannelFromDataSource, Comment, CommentFromDataSource } from './index.js'

export type ThreadId = number;

export interface ThreadFromDataSource {
	id: ThreadId;
	channelId: ChannelFromDataSource['id'];
	title?: string;
	autogeneratedTitle?: string;
	createdAt?: Date;
	updatedAt?: Date;
	afterCommentId?: CommentFromDataSource['id'];
	commentsCount: number;
	attachmentsCount: number;
	commentAttachmentsCount: number;
	uniquePostersCount?: number;
	comments: CommentFromDataSource[];
	latestComments?: CommentFromDataSource[];
	pinned?: boolean;
	pinnedOrder?: number;
	locked?: boolean;
	trimming?: boolean;
	archived?: boolean;
	archivedAt?: Date;
	bumpLimitReached?: boolean;
	attachmentLimitReached?: boolean;
	customSpoilerId?: number;
	channel?: ChannelFromDataSource;
}

export interface Thread extends ThreadFromDataSource {
	// When a user hasn't disabled censoring offensive words,
	// the thread title will be checked for such words.
	titleCensored?: string;
	titleCensoredContent?: InlineContent;

	// Whether some or all of the comments in this thread have "author ID" hashes
	// that can be displayed for the comments in order to publicly semi-identify their author
	// while preserving some degree of anynymity.
	hasAuthorIds?: boolean;

	comments: Comment[];
	latestComments?: Comment[];

	// Thread page periodically refreshes itself for new comments.
	// If during such refresh the "get thread" API starts returning a "Not found" response
	// then the thread gets marked as "expired". Perhaps this property should be called "deleted".
	expired?: true;

	// When displaying a list of threads on a channel, the first item in the list might be rendered
	// with slightly different spacing.
	// * In `api/getThreads.ts` it sets `isFirstThreadInTheList` property.
	// * It doesn't set this property in `api/getThread.ts`.
	isFirstThreadInTheList?: boolean;
}