import hasAttachmentPicture from 'social-components/commonjs/utility/attachment/hasPicture'
import getThumbnailSize from 'social-components/commonjs/utility/attachment/getThumbnailSize'

import UserData from '../UserData/UserData'

export default function createTrackedThreadRecord(thread, channel) {
	const latestComment = thread.comments[thread.comments.length - 1]
	const trackedThread = {
		id: thread.id,
		// The `#${thread.id}` part is just in case the thread
		// both doesn't have a title and a title wasn't autogenerated
		// for some reason (perhaps missing `messages` for "Picture", etc).
		title: thread.titleCensored || thread.title,
		channel: {
			id: channel.id,
			title: channel.title
		},
		// "rolling" thread status is not stored in a "tracked thread"
		// record because it might change in future: for example, a thread
		// could be a regular one, but then a moderator makes it into a
		// rolling thread. So, `trackedThreadRecord.rolling` flag could
		// become stale, and, therefore, it's not used.
		// rolling: thread.isRolling,
		latestComment: createTrackedThreadRecordLatestComment(latestComment, {
			isRolling: thread.isRolling
		})
	}
	const thumbnailAttachment = thread.comments[0].attachments &&
			thread.comments[0].attachments.filter(hasAttachmentPicture)[0]
	if (thumbnailAttachment) {
		const thumbnail = getThumbnailSize(thumbnailAttachment)
		trackedThread.thumbnail = {
			type: thumbnail.type,
			url: thumbnail.url,
			width: thumbnail.width,
			height: thumbnail.height
		}
		if (thumbnailAttachment.spoiler) {
			trackedThread.thumbnail.spoiler = true
		}
	}
	return trackedThread
}

export function createTrackedThreadRecordLatestComment(latestComment, { isRolling }) {
	const latestCommentInfo = {
		id: latestComment.id,
		createdAt: latestComment.createdAt.getTime()
	}
	if (!isRolling) {
		latestCommentInfo.i = latestComment.indexForLatestReadCommentDetection
	}
	return latestCommentInfo
}

/**
 * Tells if there're any new (unread) comments in a tracked thread.
 * @param  {object} trackedThread — Tracked thread record from `UserData`.
 * @return {boolean} [areThereAnyNewComments] Returns `undefined` if it's unknown whether there're any new comments.
 */
function _areThereAnyNewComments(trackedThread) {
	const latestReadComment = UserData.getLatestReadComment()
	if (!latestReadComment) {
		return true
	}
	// Sometimes, only `trackedThread.latestComment.i` exists, and not the `.id`.
	// The reason is that `/catalog.json` API response doesn't provide any comment ids,
	// but does provide the overall comments count, from which the
	// `trackedThread.latestComment.i` is calculated.
	//
	// "Rolling" tracked threads don't have comment indexes stored
	// because those're pointless because old comments get erased
	// as new comments are added.
	//
	const isLatestCommentIdStored = trackedThread.latestComment.id !== undefined
	if (isLatestCommentIdStored) {
		return trackedThread.latestComment.id > latestReadComment.id
	} else if (trackedThread.latestComment.i !== undefined) {
		return trackedThread.latestComment.i > latestReadComment.i
	}
}