import './types/value.test'
import './types/list.test'
import './types/map.test'

import './UserData.clear.test'
import './UserData.expire.test.js'
import './UserData.get.test.js'
import './UserData.index.test.js'
import './UserData.matchKey.test.js'
import './UserData.merge.test.js'
import './UserData.migrate.test.js'
import './UserData.onExternalChange.test.js'
import './UserData.replace.test.js'
import './UserData.storage.test.js'

import './clearUnusedThreadsData.test.js'
import './fixSubscribedThreadsData.test.js'