import { censorWords, getInlineContentText } from 'social-components/content'
import type { Thread, ThreadFromDataSource, UserSettingsJson } from '../../types/index.js'

import transformText from './transformText.js'

interface Parameters {
	locale: UserSettingsJson['locale'];
	grammarCorrection: UserSettingsJson['grammarCorrection'];
	censoredWords: UserSettingsJson['censoredWords'];
}

/**
 * Adds some utility properties on thread comments.
 *
 * It "mutates" the `thread` object because: (a) such approach doesn't cause any issues and
 * (b) it has been written like this originally so it's not very clear if changing that aspect
 * could hypothetically cause any issues.
 *
 * @param {object} thread
 * @param {object} options
 * @param {object[]} [options.censoredWords]
 */
export default function addThreadProps(threadFromDataSource: ThreadFromDataSource, {
	locale,
	grammarCorrection,
	censoredWords
}: Parameters) {
	// New properties will be added to `thread` object.
	// This assignment is to work around TypeScript errors
	// while those properties are being added one-by-one.
	const thread = threadFromDataSource as Partial<Thread>

	// Set `hasAuthorIds` flag on the `thread`.
	if (thread.comments[0].threadHasAuthorIds) {
		thread.hasAuthorIds = true
	}

	// If the thread has a title, then transform it.
	// Otherwise, autogenerate one.
	addThreadTitle(thread, {
		locale,
		grammarCorrection,
		censoredWords
	})
}

function addThreadTitle(thread: Partial<Thread>, {
	locale,
	grammarCorrection,
	censoredWords
}: {
	locale: UserSettingsJson['locale'],
	grammarCorrection: UserSettingsJson['grammarCorrection'],
	censoredWords: UserSettingsJson['censoredWords']
}) {
	// If the thread has no title, then use the title
	// generated from the original comment's content.
	if (!thread.title) {
		thread.title = thread.autogeneratedTitle
	}
	// Transform and censor thread title.
	if (thread.title) {
		thread.title = transformText(thread.title, {
			grammarCorrection,
			locale,
			replaceQuotes: true
		})
		if (censoredWords) {
			const titleCensored = censorWords(thread.title, censoredWords)
			if (titleCensored !== thread.title) {
				thread.titleCensoredContent = titleCensored
				thread.titleCensored = getInlineContentText(titleCensored)
			} else {
				thread.titleCensoredContent = thread.title
				thread.titleCensored = thread.title
			}
		}
	} else {
		// Normally, a thread will always have a title,
		// be it a title input by the thread creator,
		// or a one autogenerated from the original comment's
		// content, be it text, picture, video, etc.
		// But just in case anything weird happens,
		// a dummy thread title is added here.
		thread.title = `#${thread.id}`
	}
}