export default {
  "boardId": "v",
  "commentsCount": 17,
  "commentAttachmentsCount": 7,
  "uniquePostersCount": 18,
  "customSpoilersCount": 1,
  "id": 456354102,
  "comments": [
    {
      "id": 456354102,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/png",
            "width": 913,
            "height": 716,
            "size": 345417,
            "url": "https://i.4cdn.org/v/1553850900879.png",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 250,
                "height": 196,
                "url": "https://i.4cdn.org/v/1553850900879s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T09:15:00.000Z"),
      "inReplyTo": [],
      "content": [
        [
          {
            "type": "inline-quote",
            "content": "Stalker 2"
          },
          "\n",
          "12 years of waiting",
          "\n",
          {
            "type": "inline-quote",
            "content": "Borderlands 3"
          },
          "\n",
          "8 years of waiting",
          "\n",
          {
            "type": "inline-quote",
            "content": "Shenmue 3"
          },
          "\n",
          "19 years of waiting",
          "\n",
          {
            "type": "inline-quote",
            "content": "Vampire the masquarade bloodlines 2"
          },
          "\n",
          "16 years of waiting",
          "\n",
          {
            "type": "inline-quote",
            "content": "Devil may cry 5"
          },
          "\n",
          "11 years of waiting"
        ],
        [
          "We are going back bros"
        ]
      ],
      "replies": [
        456354139,
        456355379,
        456355448,
        456355782,
        456357639,
        456359481,
        456359839
      ],
      "textPreview": "«Stalker 2»\n12 years of waiting\n«Borderlands 3»\n8 years of waiting\n«Shenmue 3»\n19 years of waiting\n«Vampire the masquarade bloodlines 2»"
    },
    {
      "id": 456354139,
      "attachments": [],
      "createdAt": new Date("2019-03-29T09:15:39.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "wojack"
          },
          "\n",
          "Time to head on back, faglord."
        ]
      ]
    },
    {
      "id": 456354175,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/png",
            "width": 219,
            "height": 301,
            "size": 54518,
            "url": "https://i.4cdn.org/v/1553850973138.png",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 90,
                "height": 125,
                "url": "https://i.4cdn.org/v/1553850973138s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T09:16:13.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "all epic store exclusives"
        ]
      ],
      "replies": [
        456354990,
        456357440
      ]
    },
    {
      "id": 456354990,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/jpeg",
            "width": 421,
            "height": 440,
            "size": 33680,
            "url": "https://i.4cdn.org/v/1553851874421.jpg",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 119,
                "height": 125,
                "url": "https://i.4cdn.org/v/1553851874421s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T09:31:14.000Z"),
      "inReplyTo": [
        456354175
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354175,
            "content": "Сообщение",
            "url": "/v/456354102#456354175",
            "quote": "all epic store exclusives",
            "quoteAutogenerated": true
          }
        ]
      ],
      "replies": [
        456357440
      ]
    },
    {
      "id": 456355259,
      "attachments": [],
      "createdAt": new Date("2019-03-29T09:36:53.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "Can we stop going back already? Everything was shit back then."
        ]
      ]
    },
    {
      "id": 456355312,
      "attachments": [],
      "createdAt": new Date("2019-03-29T09:37:52.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "Still not Metropolismania 3"
        ],
        [
          "it hurts"
        ]
      ]
    },
    {
      "id": 456355379,
      "attachments": [],
      "createdAt": new Date("2019-03-29T09:39:04.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "12 years of waiting\n8 years of waiting\n«Shenmue 3»\n19 years of waiting\n«Vampire the masquarade bloodlines 2»\n16 years of waiting\n«Devil may cry 5»",
            "quoteAutogenerated": true
          },
          "\n",
          "Let's have a MGR2 to complete this.",
          "\n",
          "If it's announced this year, the game would release next year (probably) ",
          "\n",
          "So this would mean : 7 years of waiting...time really is fast."
        ]
      ]
    },
    {
      "id": 456355448,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/jpeg",
            "width": 249,
            "height": 207,
            "size": 6854,
            "url": "https://i.4cdn.org/v/1553852430591.jpg",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 125,
                "height": 103,
                "url": "https://i.4cdn.org/v/1553852430591s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T09:40:30.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "WoW classic coming out this summer"
          },
          "\n",
          "feels good to be back bros"
        ]
      ]
    },
    {
      "id": 456355782,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/png",
            "width": 1334,
            "height": 750,
            "size": 2749450,
            "url": "https://i.4cdn.org/v/1553852845568.png",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 124,
                "height": 70,
                "url": "https://i.4cdn.org/v/1553852845568s.jpg"
              },
              {
                "type": "image/jpeg",
                "width": 1024,
                "height": 576,
                "url": "https://i.4cdn.org/v/1553852845568m.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T09:47:25.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "12 years of waiting\n8 years of waiting\n«Shenmue 3»\n19 years of waiting\n«Vampire the masquarade bloodlines 2»\n16 years of waiting\n«Devil may cry 5»",
            "quoteAutogenerated": true
          },
          "\n",
          "I’m glad people is happy and getting their favorite franchises back, but I hate sequels. In most cases is just an uninspired cashgrab and it just gets worse after every single release. If you really have a passion project you can really put time in a single release, but I guess this industry works more and more like holowood, were the original ideas run thin and the new fad is exploiting nostalgia and popular series."
        ]
      ]
    },
    {
      "id": 456356146,
      "attachments": [],
      "createdAt": new Date("2019-03-29T09:54:54.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "Stalker fulfill this time period with mods"
        ]
      ]
    },
    {
      "id": 456357440,
      "attachments": [],
      "createdAt": new Date("2019-03-29T10:20:03.000Z"),
      "inReplyTo": [
        456354175,
        456354990
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354175,
            "content": "Сообщение",
            "url": "/v/456354102#456354175",
            "quote": "all epic store exclusives",
            "quoteAutogenerated": true
          },
          "\n",
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354990,
            "content": "Сообщение",
            "url": "/v/456354102#456354990",
            "quote": "«all epic store exclusives»",
            "quoteAutogenerated": true
          },
          "\n",
          "CHINK SHILL BTFO"
        ]
      ]
    },
    {
      "id": 456357514,
      "attachments": [],
      "createdAt": new Date("2019-03-29T10:21:16.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "haha wow",
          "\n",
          "where'd you get these new feelman pics"
        ]
      ]
    },
    {
      "id": 456357639,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/jpeg",
            "width": 680,
            "height": 534,
            "size": 27639,
            "url": "https://i.4cdn.org/v/1553855038405.jpg",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 125,
                "height": 98,
                "url": "https://i.4cdn.org/v/1553855038405s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T10:23:58.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "ori and will of the wisps"
          },
          "\n",
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "cuphead dlc"
          },
          "\n",
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "DMC 5"
          },
          "\n",
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "Rage2"
          },
          "\n",
          "What a time to be a Bloomer"
        ]
      ]
    },
    {
      "id": 456357863,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/jpeg",
            "width": 1280,
            "height": 1063,
            "size": 146709,
            "url": "https://i.4cdn.org/v/1553855294572.jpg",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 125,
                "height": 103,
                "url": "https://i.4cdn.org/v/1553855294572s.jpg"
              },
              {
                "type": "image/jpeg",
                "width": 1024,
                "height": 850,
                "url": "https://i.4cdn.org/v/1553855294572m.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T10:28:14.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "You forgot WoW Classic and Halo PC"
        ],
        [
          {
            "type": "inline-quote",
            "content": "Old friend I knew since I was 4 texts me about Halo PC being announced"
          },
          "\n",
          {
            "type": "inline-quote",
            "content": "Haven't seen since we both went off to college"
          },
          "\n",
          {
            "type": "inline-quote",
            "content": "Tells me he's building a PC this summer"
          },
          "\n",
          {
            "type": "inline-quote",
            "content": "Wants to bring the squad back together"
          }
        ],
        [
          "WE'RE COMING HOME"
        ]
      ]
    },
    {
      "id": 456359481,
      "attachments": [],
      "createdAt": new Date("2019-03-29T10:57:02.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "Sonic Adventure 3"
          },
          "\n",
          "17 Years of waiting",
          "\n",
          {
            "type": "inline-quote",
            "content": "Mega Man X9"
          },
          "\n",
          "15 Years of waiting"
        ],
        [
          "How long for me, /v/ros?"
        ]
      ]
    },
    {
      "id": 456359763,
      "attachments": [],
      "createdAt": new Date("2019-03-29T11:01:46.000Z"),
      "inReplyTo": [],
      "content": [
        [
          "I'm probably going to upgrade my pc when Stalker 2 releases for the optimal experience."
        ]
      ]
    },
    {
      "id": 456359839,
      "attachments": [],
      "createdAt": new Date("2019-03-29T11:03:23.000Z"),
      "inReplyTo": [
        456354102
      ],
      "content": [
        [
          {
            "type": "post-link",
            "boardId": "v",
            "threadId": 456354102,
            "postId": 456354102,
            "content": "Сообщение",
            "url": "/v/456354102#456354102",
            "quote": "they're all massive disappointments"
          }
        ]
      ]
    },
    {
      "id": 456360063,
      "attachments": [
        {
          "type": "picture",
          "picture": {
            "type": "image/jpeg",
            "width": 694,
            "height": 842,
            "size": 75745,
            "url": "https://i.4cdn.org/v/1553857623792.jpg",
            "sizes": [
              {
                "type": "image/jpeg",
                "width": 103,
                "height": 125,
                "url": "https://i.4cdn.org/v/1553857623792s.jpg"
              }
            ]
          }
        }
      ],
      "createdAt": new Date("2019-03-29T11:07:03.000Z"),
      "inReplyTo": [],
      "content": [
        [
          {
            "type": "inline-quote",
            "content": "Half-Life 3"
          },
          "\n",
          "Never."
        ]
      ]
    }
  ]
}